import '../models/user_roles.dart';

enum RolePermission {
  viewMarketplace,
  viewServiceDetail,
  purchaseServices,
  checkoutService,
  viewOrders,
  manageBuyerOrders,
  manageSellerOrders,
  manageOwnServices,
  accessSellerDashboard,
  accessAdminConsole,
  moderateServices,
  manageTransactions,
  managePayouts,
  viewDashboard,
  viewBids,
  manageBids,
  viewChats,
  viewOwnJobs,
  viewJobs,
  createJob,
  acceptJob,
  completeJob,
  cancelJob,
  payJob,
  viewNotifications,
  viewWallet,
  releasePayment,
}

const Map<UserRoles, Set<RolePermission>> kRolePermissions = {
  UserRoles.admin: {
    RolePermission.viewMarketplace,
    RolePermission.viewServiceDetail,
    RolePermission.purchaseServices,
    RolePermission.checkoutService,
    RolePermission.viewOrders,
    RolePermission.manageBuyerOrders,
    RolePermission.manageSellerOrders,
    RolePermission.manageOwnServices,
    RolePermission.accessSellerDashboard,
    RolePermission.accessAdminConsole,
    RolePermission.moderateServices,
    RolePermission.manageTransactions,
    RolePermission.managePayouts,
    RolePermission.viewDashboard,
    RolePermission.viewBids,
    RolePermission.manageBids,
    RolePermission.viewChats,
    RolePermission.viewOwnJobs,
    RolePermission.viewJobs,
    RolePermission.createJob,
    RolePermission.acceptJob,
    RolePermission.completeJob,
    RolePermission.cancelJob,
    RolePermission.payJob,
    RolePermission.viewNotifications,
    RolePermission.viewWallet,
    RolePermission.releasePayment,
  },
  UserRoles.manager: {
    RolePermission.viewMarketplace,
    RolePermission.viewServiceDetail,
    RolePermission.viewOrders,
    RolePermission.manageSellerOrders,
    RolePermission.manageBuyerOrders,
    RolePermission.manageOwnServices,
    RolePermission.accessSellerDashboard,
    RolePermission.accessAdminConsole,
    RolePermission.moderateServices,
    RolePermission.manageTransactions,
    RolePermission.managePayouts,
    RolePermission.viewDashboard,
    RolePermission.viewBids,
    RolePermission.manageBids,
    RolePermission.viewChats,
    RolePermission.viewJobs,
    RolePermission.viewNotifications,
    RolePermission.viewWallet,
    RolePermission.releasePayment,
    RolePermission.viewOwnJobs,
    RolePermission.createJob,
    RolePermission.acceptJob,
    RolePermission.completeJob,
    RolePermission.cancelJob,
    RolePermission.payJob,
  },
  UserRoles.support: {
    RolePermission.viewMarketplace,
    RolePermission.viewServiceDetail,
    RolePermission.viewOrders,
    RolePermission.viewDashboard,
    RolePermission.viewBids,
    RolePermission.viewChats,
    RolePermission.viewJobs,
    RolePermission.viewNotifications,
    RolePermission.viewWallet,
  },
  UserRoles.client: {
    RolePermission.viewMarketplace,
    RolePermission.viewServiceDetail,
    RolePermission.purchaseServices,
    RolePermission.checkoutService,
    RolePermission.viewOrders,
    RolePermission.manageBuyerOrders,
    RolePermission.viewDashboard,
    RolePermission.viewChats,
    RolePermission.viewOwnJobs,
    RolePermission.viewJobs,
    RolePermission.createJob,
    RolePermission.cancelJob,
    RolePermission.payJob,
    RolePermission.viewNotifications,
    RolePermission.viewWallet,
  },
  UserRoles.freelancer: {
    RolePermission.viewMarketplace,
    RolePermission.viewServiceDetail,
    RolePermission.viewOrders,
    RolePermission.manageSellerOrders,
    RolePermission.manageOwnServices,
    RolePermission.accessSellerDashboard,
    RolePermission.viewDashboard,
    RolePermission.viewBids,
    RolePermission.manageBids,
    RolePermission.viewChats,
    RolePermission.viewJobs,
    RolePermission.acceptJob,
    RolePermission.completeJob,
    RolePermission.viewNotifications,
    RolePermission.viewWallet,
  },
  UserRoles.seller: {
    RolePermission.viewMarketplace,
    RolePermission.viewServiceDetail,
    RolePermission.viewOrders,
    RolePermission.manageSellerOrders,
    RolePermission.manageOwnServices,
    RolePermission.accessSellerDashboard,
    RolePermission.viewDashboard,
    RolePermission.viewBids,
    RolePermission.manageBids,
    RolePermission.viewChats,
    RolePermission.viewJobs,
    RolePermission.acceptJob,
    RolePermission.completeJob,
    RolePermission.viewNotifications,
    RolePermission.viewWallet,
    RolePermission.releasePayment,
  },
};

bool can(UserRoles role, RolePermission permission) {
  final permissions = kRolePermissions[role];
  if (permissions == null) {
    return false;
  }
  return permissions.contains(permission);
}
